token:
  expiration_time: 86400000
  secret: user_token_ecommerce_dev

gateway:
  ip: 127.0.0.1

spring:
  datasource:
    driver-class-name: '{cipher}AQBAMWsr6ZPKvaEpn+HJQVbMq71i3zLLQV3s82+GyRAquxSbhpv2fX/5Jx1DwtNwztsPzbJIq85XfDBbE4IvqRyqQ1+nfNBZke4ctP0hzYkgAPLHHJjVwCXbw0hHc/A6Yz/o11If7r/LWznfaOcJgDzWF1R0kPn/zt2VHtyO9cfh5xPZyLedoIV2RwyW4lUIT7ezLvgeKAieQn/cD4A/IiuRIjqLuF1alSZgdFt5S2iEZ+yt986g3dcEjDAXD6l1GzY89mfhWpZkpGF9vTMe830b5hmlVczPfsJhE3pijahkJuO16X6pJR682NjVh3vVdVG5prPO8uxptYkwvFFkGgaPvcR4LQuueUA3UmwHTSA0MwCrzoDzLUEydd1sLR8ULqY='
    url: '{cipher}AQBASZConopPNjZejpTI2mDTygpbJMYFqdvYp4xm9v+2vG5dojbox5cg0sntxJbcH0cNGm4H3kfrbJahK/YJr6p8nJvZLOaajf9kiBAML7vjcBmKCqbQa9Iz6ABEJEl2qwDdX7rHzNbIdcVQtBdPmwjEVzg2phPe3V6TWZgbFCPYyIO4JDfuQnWpnV22Grdnp6xKeedVY8LOvOqjoqqd82M09sCK05YpmB0oIwK2WOotQw2XLqm6Ue7N1gpXfYPDldiDPBSh96wjD0hpXd4TlwedUtrxqU39neBgXjAhQMlKs60s8DtOwtCDRccEI8JElbPkOqReBW0Ltmyw5gTPdy+mPvTyvv+PaGvT9FfR0LLWzorM3r+u5lXMTZWn+5ths++jlzFuYYNMYdP9gSviMc/9'
