token:
  expiration_time: 86400000
  secret: user_token_ecommerce_dev

gateway:
  ip: 127.0.0.1

spring:
  datasource:
    driver-class-name: '{cipher}AQAXi0Y/4TDbFRoneYGEQ8rEr2NhMuMGbqAp5cpzfFZZivJDvpuj2mOoXIbTVuTI3PYHXc7Wc+HqOjhg3UxdkrffGyY6h6qi2zVHkmhrHHJKcylvjCceTvwuDuUyfXf4qEks+L5Wy8iTMXlhS0pMtQFRo0BzzC6yx8pbbKqX2bYpg8BzpH2J6qCD6CApteeYkf0+869T67/2rRHWigzR8YuSpY0vGJtd4MWPnicNpl4auGqPPl11rs3ji4zrV+UhQdWtswelS6JEJfZWU1icQILowAZVemDWY4mUxHk6QxlpYmgA+d3AVfi9ig9+cFiThqykF7dV7gL1hKnGM617yoMfSXG2QtYs2u44vVbpmg1hD3EhuJzh/8adMbrobMCifb8='
    url: '{cipher}AQBl8nwhWn76FDPi3XqPsSSYNAwT6ZISMZmyFK/agNXd1q42a1F6I3zqvTM6KTK8mYrv5SPVZXr12PDFXcYsL6d5xO3/Ya9zuDapXzsAges/lQD+ZUIarJiCer/xuyLDjsXFUwKQwasUFcnm4oSgFdPa6Eowj40fi0mn9KfnS9OlA6LmKnwCb67JOSpuez+mOJNGTTlT2zheYxPkC7PZ0+xYkojAjeoaO/hey2HVMJdpfGUEHOvvVCAm0VMFHxzoyFr7qmz7WJtyhu7W+Gk4G2EMhrMPkGOYyBLb7LqBL+dOryYdb8qFa7mXj0Rg38DaUno2wNWjtdlPfqNSX26EdfZUQPsFjRe7Fw5H1nfJ1TBJ6zNJZ36JReMsX9XMffFA3DGVHWt/l0AfTK0BstDk8D6t'


order_service:
  url: http://127.0.0.1:8000/order-service/%s/orders
